#!/usr/bin/env php
<?php
$url="http://api.apixu.com/v1/current.json?key=452bb5cfe3cf4e4f80b194001190803&q=$argv[1]";

$json=@file_get_contents($url);
if ($json) {
	$obj=json_decode($json);
	echo $obj->current->temp_c; 
} else {
	echo "Error";
}
